sudo: false
language: node_js

node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"

env:
  - COVERAGE=false

matrix:
  fast_finish: true
  include:
    - node_js: "6"
      env: COVERAGE=true
      script: "npm run codeclimate"
  allow_failures:
    - node_js: "6"
      env: COVERAGE=true
      script: "npm run codeclimate"

before_script:
  - npm prune
after_success:
  - travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
