language: node_js

node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"

env:
  - COVERAGE=false

matrix:
  fast_finish: true
  include:
    - node_js: "0.12"
      env: COVERAGE=true
      script: "npm run codeclimate"
  allow_failures:
    - node_js: "0.12"
      env: COVERAGE=true
      script: "npm run codeclimate"