sudo: false
language: node_js

node_js:
  - "18"
  - "17"
  - "16"
  - "14"
  - "12"

env:
  - COVERAGE=false

matrix:
  fast_finish: true
  include:
    - node_js: "12"
      env: COVERAGE=true
      script:
        - "npm run cover"
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      script: 
        - npm run build
        - npm run semantic-release
  allow_failures:
    - node_js: "12"
      env: COVERAGE=true
      script:
        - "npm run cover"
        - bash <(curl -s https://codecov.io/bash)

script:
  - npm run lint
  - npm t
  - npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
